import { headingFont, bodyFont } from "@/lib/fonts";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import { ui } from "@clerk/ui";
import Header from "@/components/Header";
import { Toaster } from "sonner";



export const metadata = {
  title: "Oralix",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider ui={ui} appearance={{
      theme:dark
    }}>
      <html
        lang="en" suppressHydrationWarning>
        <body className={`${headingFont.variable} ${bodyFont.variable} font-sans bg-black text-white`}>
          <div className="bg-black">
          <div className="w-full lg:mx-auto lg:max-w-362.5 border-l border-r border-neutral-800">
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>

              {/*<Header />*/}
              <Header/>

              <main className="max-w-full"> {children}</main>

              <Toaster richColors/>

              {/*<Footer />*/}

            </ThemeProvider>
            </div>
            </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
