import { headingFont, bodyFont } from "@/lib/fonts";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { ClerkProvider} from '@clerk/nextjs'
import { dark } from "@clerk/themes";
import Header from "@/components/Header";



export const metadata = {
  title: "Oralix",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      theme:dark
    }}>
      <html
        lang="en" suppressHydrationWarning>
        <body className={`${headingFont.variable} ${bodyFont.variable} font-sans`}>
          <div className="bg-black">
          <div className="w-full  lg:mx-auto lg:max-w-[1450px]  border-l border-r border-neutral-800">
          <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange>

              {/*<Header />*/}
              <Header/>

              <main className="max-w-full"> {children}</main>

              {/*<Footer />*/}

            </ThemeProvider>
            </div>
            </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
